services:
  postgresql:
    image: postgres:16
    container_name: psql-app
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - inkflow_postgres_data:/var/lib/postgresql/data
    networks:
      - inkFlow

networks:
  inkFlow:

volumes:
  inkflow_postgres_data: